### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by paulovictoraa** [paulovictoraa/teste-catho#1]
- [ ] Localizador de Cidades

- [ ] Regra do salário
 
- [ ] Regra de ocultação do salário

- [ ] Imagem do Perfil

- [ ] Nome do Perfil

- [ ] Adicionar animação no SplashScreen.

- [ ] Ajustar layout wrap_content

- [ ] POST do like/deslike

- [ ] Botão dinâmico

- [ ] Link para acesso ao clicar no botão
